### ISSUE TITLE
getting internal server error while adding vNet to block using API

### ISSUE THREAD

**Issue by vpgohil** [Azure/ipam#20]
Hi,

I am trying to add vNet to block named aks in space azure.
I am able to do it using UI but when I try to do it using API I am getting "internal server error".
below you can find logs from app service,.

`2022-07-07T10:36:49.995300252Z INFO:     172.16.4.4:52062 - "POST /api/spaces/azure/blocks/aks/networks HTTP/1.0" 500 Internal Server Error
2022-07-07T10:36:49.995841161Z ERROR:    Exception in ASGI application
2022-07-07T10:36:49.995898662Z Traceback (most recent call last):
2022-07-07T10:36:49.995904962Z   File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 372, in run_asgi
2022-07-07T10:36:49.995910362Z     result = await app(self.scope, self.receive, self.send)
2022-07-07T10:36:49.995915962Z   File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
2022-07-07T10:36:49.995920963Z     return await self.app(scope, receive, send)
2022-07-07T10:36:49.995925263Z   File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 269, in __call__
2022-07-07T10:36:49.995929963Z     await super().__call__(scope, receive, send)
2022-07-07T10:36:49.995934463Z   File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 124, in __call__
2022-07-07T10:36:49.995939563Z     await self.middleware_stack(scope, receive, send)
2022-07-07T10:36:49.995945063Z   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
2022-07-07T10:36:49.995957663Z     raise exc
2022-07-07T10:36:49.995962863Z   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
2022-07-07T10:36:49.995967863Z     await self.app(scope, receive, _send)
2022-07-07T10:36:49.995972363Z   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 84, in __call__
2022-07-07T10:36:49.995977463Z     await self.app(scope, receive, send)
2022-07-07T10:36:49.995981864Z   File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 93, in __call__
2022-07-07T10:36:49.995987064Z     raise exc
2022-07-07T10:36:49.996006964Z   File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
2022-07-07T10:36:49.996012364Z     await self.app(scope, receive, sender)
2022-07-07T10:36:49.996016964Z   File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
2022-07-07T10:36:49.996871979Z     raise e
2022-07-07T10:36:49.996890779Z   File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
2022-07-07T10:36:49.996897379Z     await self.app(scope, receive, send)
2022-07-07T10:36:49.996902179Z   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 670, in __call__
2022-07-07T10:36:49.996907179Z     await route.handle(scope, receive, send)
2022-07-07T10:36:49.996912179Z   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 266, in handle
2022-07-07T10:36:49.996917179Z     await self.app(scope, receive, send)
2022-07-07T10:36:49.996921779Z   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 65, in app
2022-07-07T10:36:49.996926679Z     response = await func(request)
2022-07-07T10:36:49.996933280Z   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 227, in app
2022-07-07T10:36:49.996938480Z     raw_response = await run_endpoint_function(
2022-07-07T10:36:49.996943180Z   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
2022-07-07T10:36:49.996948080Z     return await dependant.call(**values)
2022-07-07T10:36:49.996953180Z   File "/code/./app/routers/space.py", line 866, in create_block_vnet
2022-07-07T10:36:49.996958380Z     target = next((x for x in vnet_list if x['id'].lower() == v.lower()), None)
2022-07-07T10:36:49.996963480Z   File "/code/./app/routers/space.py", line 866, in <genexpr>
2022-07-07T10:36:49.996968880Z     target = next((x for x in vnet_list if x['id'].lower() == v.lower()), None)
2022-07-07T10:36:49.996973580Z AttributeError: 'dict' object has no attribute 'lower'
2022-07-07T10:36:49.996738276Z 172.16.4.1 - - [07/Jul/2022:10:36:49 +0000] "POST /api/spaces/azure/blocks/aks/networks HTTP/1.1" 500 21 "-" "PostmanRuntime/7.29.0"`

**Comment by DCMattyG** [comment]
Hi @vpgohil, looking at the line referenced in the error message above, it seems you may be running a previous version of the IPAM container. Please stop/start the Azure App Service, and give it a few minutes to download the latest version of the containers. Hopefully this will address your issue.

Just for your knowledge, when you add networks from the UI, it uses a PUT to update the entire list at once. This is why you were seeing a discrepancy between it working it the UI, and failing when you performed a POST locally.

**Comment by DCMattyG** [comment]
Hey @vpgohil, thanks for the feedback. It seems the latest source code may not have been built into the latest container images. I just built the new containers and pushed them to the ACR. Please try stopping/starting the App Service one more time to allow it to pull the new images, and then let me know if you're still experiencing the same behavior. Thanks for all of the feedback!

**Comment by vpgohil** [comment]
Hi @DCMattyG , I am still getting same error.

**Comment by DCMattyG** [comment]
@vpgohil, I'm happy to do a 1:1 session with you to figure out why you're seeing this behavior. Please feel free to reach out to me at Matthew.Garrett@microsoft.com so we can find a time that works best between us.

**Comment by DCMattyG** [comment]
Hi @vpgohil, closing this issue as we spoke 1:1 and have confirmed this specific issue has been resolved. Please reach out if anything else comes up and we'll address it right away. Thanks!
