### ISSUE TITLE
vNets in Block becoming unassociated and duplicated

### ISSUE THREAD

**Issue by jkieffer0616** [Azure/ipam#205]
**Describe the bug**
When I go in to Block Networks I will see a vNet in red with ErrNotFound but I will also see a different row with the exact same vNet that is unchecked (not associated) so I have to uncheck the Not Found one and check the found one to get it to associate again.  Almost every day this happens and it's not always with the same vNets.  Sometimes it's just one, sometimes it's more than one.  Nothing has changed with the vNet on the Azure side except maybe creating/deleting subnets.

![image](https://github.com/Azure/ipam/assets/57921923/4ae719fd-cb8b-49db-8ace-c7fe412669ec)

**To Reproduce**
Can't force it to reproduce but if I go to Block Networks I will see the duplicate vNets (one red with ErrNotFound, the other is not associated even though at one time it was associated)

**Expected behavior**
Once associated the vNet should stay associated until it association is removed.

**Screenshots**
![image](https://github.com/Azure/ipam/assets/57921923/31d48f9e-485a-4be3-9cf8-7566de74302f)

**Comment by DCMattyG** [comment]
Hi @jkieffer0616, I was going through all of the current open issues & discussions and realized that I never responded to you on this item and I'm very sorry for that!

I did add some code fixes to the UI a while back to attempt to address this problem that you are seeing. Can you let me know if this is still happening in your environment? I definitely want to make sure we get to the bottom of this together as I'm never satisfied until all of the issues are addressed and everyone is having a great experience with the Azure IPAM solution.

Let me know if you're still seeing this and I'll make sure to focus on a proper resolution for you here. Thank you!

**Comment by jkieffer0616** [comment]
@DCMattyG  - I will update to the latest code version, try it out, and let you know if I still see the issue.  Thanks!

**Comment by DCMattyG** [comment]
Hey there @jkieffer0616, we've just released **v3.0.0** so the latest containers are available.

Have you been able to test if the UI fixed I implemented have addressed your situation with the duplicate entries appearing?

Please let me know how things are going when you can, thanks!

**Comment by jkieffer0616** [comment]
Hi @DCMattyG  - I updated all of the container images successfully except UI which I get an error.  Any thoughts?  Also, is there an easy way to update to the newer, single container, deployment while keeping the same resources (DB, MI, etc?)

az acr build -r <ACR Name> -t ipam-ui:latest -f ./ui/Dockerfile.deb ./ui

x Build failed in 86ms
error during build:
RollupError: Could not resolve "./index.css" from "src/index.jsx"
file: /ipam/src/index.jsx
    at error (file:///ipam/node_modules/rollup/dist/es/shared/parseAst.js:337:30)
    at ModuleLoader.handleInvalidResolvedId (file:///ipam/node_modules/rollup/dist/es/shared/node-entry.js:17969:24)
    at file:///ipam/node_modules/rollup/dist/es/shared/node-entry.js:17929:26
The command '/bin/sh -c npm run build' returned a non-zero code: 1
2024/03/05 15:52:01 Container failed during run: build. No retries remaining.
failed to run step ID: build: exit status 1

Run ID: chd failed after 37s. Error: failed during run, err: exit status 1
Run failed

**Comment by jkieffer0616** [comment]
@DCMattyG  - I was able to update the containers and will keep an eye on it to see if it resolved the issue.

On a side note - is there an easy process to update from the multi-container deployment to the newer, single container deployment?

**Comment by DCMattyG** [comment]
Hi @jkieffer0616, so great to hear that you were able to update all of the containers!

I am working on a document to walk through all of the steps on converting the original 3-container deployment to the new single container model. I'm also working on a script that will do all of the work for you as well.

Will keep you posted as soon as both of those items are ready 👍

**Comment by DCMattyG** [comment]
Since there has not been any updates on this issue for quite some time, I'm going to close this issue for now.

Additionally, as of Azure IPAM v3.6.0 there is now an update process that will migrate legacy multi-container deployments to the new single container deployment. Details can be found here: https://azure.github.io/ipam/#/update/README

If for any reason you don't feel this has been properly addressed, please feel free to re-open this issue and we can continue the discussion.

Thanks for helping to improve the Azure IPAM project!
